[project]
name = "mcp-on-cloudrun"
version = "0.1.0"
description = "Example of deploying a mcp server on cloud run"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.116.1",
    "fastmcp>=2.11.2",
]
